package Model;
// Generated Jul 2, 2015 6:45:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private Set<UserRoles> userRoleses = new HashSet<>(0);

    public Roles() {
    }

	
    public Roles(int id) {
        this.id = id;
    }
    public Roles(int id, String name, String description, Set<UserRoles> userRoleses) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.userRoleses = userRoleses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<UserRoles> getUserRoleses() {
        return this.userRoleses;
    }
    
    public void setUserRoleses(Set<UserRoles> userRoleses) {
        this.userRoleses = userRoleses;
    }




}


