package Model;
// Generated Jul 2, 2015 6:45:19 PM by Hibernate Tools 4.3.1



/**
 * UserRoles generated by hbm2java
 */
public class UserRoles  implements java.io.Serializable {


     private int id;
     private Roles roles;
     private User user;

    public UserRoles() {
    }

    public UserRoles(int id, Roles roles, User user) {
       this.id = id;
       this.roles = roles;
       this.user = user;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


